# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 599)
        MainWindow.setMinimumSize(QtCore.QSize(802, 599))
        MainWindow.setMaximumSize(QtCore.QSize(802, 599))
        MainWindow.setWindowTitle("Cedrata Detector")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.label = QtWidgets.QLabel(self.home_tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 781, 551))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.home_tab, "")
        self.classify_tab = QtWidgets.QWidget()
        self.classify_tab.setObjectName("classify_tab")
        self.layoutWidget = QtWidgets.QWidget(self.classify_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 751, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.classify_gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.classify_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.classify_gridLayout.setObjectName("classify_gridLayout")
        self.classify_source_verticalLayout = QtWidgets.QVBoxLayout()
        self.classify_source_verticalLayout.setObjectName("classify_source_verticalLayout")
        self.classify_source_label = QtWidgets.QLabel(self.layoutWidget)
        self.classify_source_label.setObjectName("classify_source_label")
        self.classify_source_verticalLayout.addWidget(self.classify_source_label)
        self.classify_source_horizontalLayout = QtWidgets.QHBoxLayout()
        self.classify_source_horizontalLayout.setObjectName("classify_source_horizontalLayout")
        self.classify_source_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.classify_source_browse.setObjectName("classify_source_browse")
        self.classify_source_horizontalLayout.addWidget(self.classify_source_browse)
        self.classify_source_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.classify_source_path.setObjectName("classify_source_path")
        self.classify_source_horizontalLayout.addWidget(self.classify_source_path)
        self.classify_source_verticalLayout.addLayout(self.classify_source_horizontalLayout)
        self.classify_gridLayout.addLayout(self.classify_source_verticalLayout, 1, 0, 1, 1)
        self.classify_destination_verticalLayout = QtWidgets.QVBoxLayout()
        self.classify_destination_verticalLayout.setObjectName("classify_destination_verticalLayout")
        self.classify_destination_select = QtWidgets.QLabel(self.layoutWidget)
        self.classify_destination_select.setObjectName("classify_destination_select")
        self.classify_destination_verticalLayout.addWidget(self.classify_destination_select)
        self.classify_destination_horizontalLayout = QtWidgets.QHBoxLayout()
        self.classify_destination_horizontalLayout.setObjectName("classify_destination_horizontalLayout")
        self.classify_destination_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.classify_destination_browse.setObjectName("classify_destination_browse")
        self.classify_destination_horizontalLayout.addWidget(self.classify_destination_browse)
        self.classify_destination_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.classify_destination_path.setObjectName("classify_destination_path")
        self.classify_destination_horizontalLayout.addWidget(self.classify_destination_path)
        self.classify_destination_verticalLayout.addLayout(self.classify_destination_horizontalLayout)
        self.classify_gridLayout.addLayout(self.classify_destination_verticalLayout, 3, 0, 1, 1)
        self.classify_relation_verticalLayout = QtWidgets.QVBoxLayout()
        self.classify_relation_verticalLayout.setObjectName("classify_relation_verticalLayout")
        self.clssify_relation_label = QtWidgets.QLabel(self.layoutWidget)
        self.clssify_relation_label.setObjectName("clssify_relation_label")
        self.classify_relation_verticalLayout.addWidget(self.clssify_relation_label)
        self.classify_relation_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.classify_relation_name.setObjectName("classify_relation_name")
        self.classify_relation_verticalLayout.addWidget(self.classify_relation_name)
        self.classify_gridLayout.addLayout(self.classify_relation_verticalLayout, 2, 0, 1, 1)
        self.classify_info_label = QtWidgets.QLabel(self.layoutWidget)
        self.classify_info_label.setObjectName("classify_info_label")
        self.classify_gridLayout.addWidget(self.classify_info_label, 0, 0, 1, 1)
        self.classify_start_horizontalLayout = QtWidgets.QHBoxLayout()
        self.classify_start_horizontalLayout.setObjectName("classify_start_horizontalLayout")
        self.classify_start_button = QtWidgets.QPushButton(self.layoutWidget)
        self.classify_start_button.setObjectName("classify_start_button")
        self.classify_start_horizontalLayout.addWidget(self.classify_start_button, 0, QtCore.Qt.AlignHCenter)
        self.classify_start_progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.classify_start_progressBar.setProperty("value", 24)
        self.classify_start_progressBar.setObjectName("classify_start_progressBar")
        self.classify_start_horizontalLayout.addWidget(self.classify_start_progressBar)
        self.classify_gridLayout.addLayout(self.classify_start_horizontalLayout, 5, 0, 1, 1)
        self.tabWidget.addTab(self.classify_tab, "")
        self.predict_tab = QtWidgets.QWidget()
        self.predict_tab.setObjectName("predict_tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.predict_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 11, 751, 501))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.predict_gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.predict_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.predict_gridLayout.setObjectName("predict_gridLayout")
        self.predict_info_label = QtWidgets.QLabel(self.layoutWidget1)
        self.predict_info_label.setObjectName("predict_info_label")
        self.predict_gridLayout.addWidget(self.predict_info_label, 0, 0, 1, 1)
        self.predict_source_verticalLayout = QtWidgets.QVBoxLayout()
        self.predict_source_verticalLayout.setObjectName("predict_source_verticalLayout")
        self.predict_source_label = QtWidgets.QLabel(self.layoutWidget1)
        self.predict_source_label.setObjectName("predict_source_label")
        self.predict_source_verticalLayout.addWidget(self.predict_source_label)
        self.predict_source_horizontalLayout = QtWidgets.QHBoxLayout()
        self.predict_source_horizontalLayout.setObjectName("predict_source_horizontalLayout")
        self.predict_source_browse = QtWidgets.QPushButton(self.layoutWidget1)
        self.predict_source_browse.setObjectName("predict_source_browse")
        self.predict_source_horizontalLayout.addWidget(self.predict_source_browse)
        self.predict_source_path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.predict_source_path.setObjectName("predict_source_path")
        self.predict_source_horizontalLayout.addWidget(self.predict_source_path)
        self.predict_source_verticalLayout.addLayout(self.predict_source_horizontalLayout)
        self.predict_gridLayout.addLayout(self.predict_source_verticalLayout, 1, 0, 1, 1)
        self.redict_start_horizontalLayout = QtWidgets.QHBoxLayout()
        self.redict_start_horizontalLayout.setObjectName("redict_start_horizontalLayout")
        self.predict_start_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.predict_start_button.setObjectName("predict_start_button")
        self.redict_start_horizontalLayout.addWidget(self.predict_start_button, 0, QtCore.Qt.AlignHCenter)
        self.predict_start_progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.predict_start_progressBar.setProperty("value", 24)
        self.predict_start_progressBar.setObjectName("predict_start_progressBar")
        self.redict_start_horizontalLayout.addWidget(self.predict_start_progressBar)
        self.predict_gridLayout.addLayout(self.redict_start_horizontalLayout, 5, 0, 1, 1)
        self.predict_destination_verticalLayout = QtWidgets.QVBoxLayout()
        self.predict_destination_verticalLayout.setObjectName("predict_destination_verticalLayout")
        self.predict_destination_select = QtWidgets.QLabel(self.layoutWidget1)
        self.predict_destination_select.setObjectName("predict_destination_select")
        self.predict_destination_verticalLayout.addWidget(self.predict_destination_select)
        self.predict_destination_horizontalLayout = QtWidgets.QHBoxLayout()
        self.predict_destination_horizontalLayout.setObjectName("predict_destination_horizontalLayout")
        self.predict_destination_browse = QtWidgets.QPushButton(self.layoutWidget1)
        self.predict_destination_browse.setObjectName("predict_destination_browse")
        self.predict_destination_horizontalLayout.addWidget(self.predict_destination_browse)
        self.predict_destination_path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.predict_destination_path.setObjectName("predict_destination_path")
        self.predict_destination_horizontalLayout.addWidget(self.predict_destination_path)
        self.predict_destination_verticalLayout.addLayout(self.predict_destination_horizontalLayout)
        self.predict_gridLayout.addLayout(self.predict_destination_verticalLayout, 3, 0, 1, 1)
        self.predict_relation_verticalLayout = QtWidgets.QVBoxLayout()
        self.predict_relation_verticalLayout.setObjectName("predict_relation_verticalLayout")
        self.predict_relation_label = QtWidgets.QLabel(self.layoutWidget1)
        self.predict_relation_label.setObjectName("predict_relation_label")
        self.predict_relation_verticalLayout.addWidget(self.predict_relation_label)
        self.predict_relation_horizontalLayout = QtWidgets.QHBoxLayout()
        self.predict_relation_horizontalLayout.setObjectName("predict_relation_horizontalLayout")
        self.predict_relation_browse = QtWidgets.QPushButton(self.layoutWidget1)
        self.predict_relation_browse.setObjectName("predict_relation_browse")
        self.predict_relation_horizontalLayout.addWidget(self.predict_relation_browse)
        self.predict_relation_path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.predict_relation_path.setObjectName("predict_relation_path")
        self.predict_relation_horizontalLayout.addWidget(self.predict_relation_path)
        self.predict_relation_verticalLayout.addLayout(self.predict_relation_horizontalLayout)
        self.predict_gridLayout.addLayout(self.predict_relation_verticalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.predict_tab, "")
        self.merge_tab = QtWidgets.QWidget()
        self.merge_tab.setObjectName("merge_tab")
        self.layoutWidget2 = QtWidgets.QWidget(self.merge_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 751, 501))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.merge_verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.merge_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.merge_verticalLayout.setObjectName("merge_verticalLayout")
        self.merge_info_label = QtWidgets.QLabel(self.layoutWidget2)
        self.merge_info_label.setObjectName("merge_info_label")
        self.merge_verticalLayout.addWidget(self.merge_info_label)
        self.merge_horizontalLayout = QtWidgets.QHBoxLayout()
        self.merge_horizontalLayout.setObjectName("merge_horizontalLayout")
        self.merge_select_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.merge_select_button.setObjectName("merge_select_button")
        self.merge_horizontalLayout.addWidget(self.merge_select_button)
        self.merge_paths_list = QtWidgets.QTextEdit(self.layoutWidget2)
        self.merge_paths_list.setObjectName("merge_paths_list")
        self.merge_horizontalLayout.addWidget(self.merge_paths_list)
        self.merge_verticalLayout.addLayout(self.merge_horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.merge_destination_label = QtWidgets.QLabel(self.layoutWidget2)
        self.merge_destination_label.setObjectName("merge_destination_label")
        self.verticalLayout.addWidget(self.merge_destination_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.merge_destination_browse = QtWidgets.QPushButton(self.layoutWidget2)
        self.merge_destination_browse.setObjectName("merge_destination_browse")
        self.horizontalLayout_2.addWidget(self.merge_destination_browse)
        self.merge_destination_path = QtWidgets.QLineEdit(self.layoutWidget2)
        self.merge_destination_path.setObjectName("merge_destination_path")
        self.horizontalLayout_2.addWidget(self.merge_destination_path)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.merge_verticalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.merge_start_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.merge_start_button.setObjectName("merge_start_button")
        self.horizontalLayout.addWidget(self.merge_start_button, 0, QtCore.Qt.AlignHCenter)
        self.merge_start_progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.merge_start_progressBar.setProperty("value", 24)
        self.merge_start_progressBar.setObjectName("merge_start_progressBar")
        self.horizontalLayout.addWidget(self.merge_start_progressBar)
        self.merge_verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.merge_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.settings_scrollArea = QtWidgets.QScrollArea(self.settings_tab)
        self.settings_scrollArea.setGeometry(QtCore.QRect(0, 0, 781, 551))
        self.settings_scrollArea.setWidgetResizable(True)
        self.settings_scrollArea.setObjectName("settings_scrollArea")
        self.settings_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.settings_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 517, 630))
        self.settings_scrollAreaWidgetContents.setObjectName("settings_scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settings_scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_predict_verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.settings_predict_verticalLayout_5.setObjectName("settings_predict_verticalLayout_5")
        self.settings_predict_overlap_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_predict_overlap_label.setObjectName("settings_predict_overlap_label")
        self.settings_predict_verticalLayout_5.addWidget(self.settings_predict_overlap_label)
        self.settings_predict_overlap_lineEdit = QtWidgets.QLineEdit(self.settings_scrollAreaWidgetContents)
        self.settings_predict_overlap_lineEdit.setObjectName("settings_predict_overlap_lineEdit")
        self.settings_predict_verticalLayout_5.addWidget(self.settings_predict_overlap_lineEdit)
        self.gridLayout_2.addLayout(self.settings_predict_verticalLayout_5, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.settings_horizontalLayout = QtWidgets.QHBoxLayout()
        self.settings_horizontalLayout.setObjectName("settings_horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.settings_horizontalLayout.addItem(spacerItem1)
        self.settings_reset_button = QtWidgets.QPushButton(self.settings_scrollAreaWidgetContents)
        self.settings_reset_button.setObjectName("settings_reset_button")
        self.settings_horizontalLayout.addWidget(self.settings_reset_button)
        self.settings_apply_button = QtWidgets.QPushButton(self.settings_scrollAreaWidgetContents)
        self.settings_apply_button.setObjectName("settings_apply_button")
        self.settings_horizontalLayout.addWidget(self.settings_apply_button)
        self.gridLayout_2.addLayout(self.settings_horizontalLayout, 10, 0, 1, 1)
        self.settings_predict_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_predict_label.setObjectName("settings_predict_label")
        self.gridLayout_2.addWidget(self.settings_predict_label, 6, 0, 1, 1)
        self.settings_classify_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.settings_classify_verticalLayout_2.setObjectName("settings_classify_verticalLayout_2")
        self.settings_classify_window_len_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_classify_window_len_label.setObjectName("settings_classify_window_len_label")
        self.settings_classify_verticalLayout_2.addWidget(self.settings_classify_window_len_label)
        self.settings_classify_window_len_lineEdit = QtWidgets.QLineEdit(self.settings_scrollAreaWidgetContents)
        self.settings_classify_window_len_lineEdit.setObjectName("settings_classify_window_len_lineEdit")
        self.settings_classify_verticalLayout_2.addWidget(self.settings_classify_window_len_lineEdit)
        self.gridLayout_2.addLayout(self.settings_classify_verticalLayout_2, 3, 0, 1, 1)
        self.settings_predict_verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.settings_predict_verticalLayout_3.setObjectName("settings_predict_verticalLayout_3")
        self.settings_predict_features_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_predict_features_label.setObjectName("settings_predict_features_label")
        self.settings_predict_verticalLayout_3.addWidget(self.settings_predict_features_label)
        self.settings_predict_verticalLayout = QtWidgets.QVBoxLayout()
        self.settings_predict_verticalLayout.setObjectName("settings_predict_verticalLayout")
        self.settings_predict_mean_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_predict_mean_checkbox.setObjectName("settings_predict_mean_checkbox")
        self.settings_predict_verticalLayout.addWidget(self.settings_predict_mean_checkbox)
        self.settings_predict_variance_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_predict_variance_checkbox.setObjectName("settings_predict_variance_checkbox")
        self.settings_predict_verticalLayout.addWidget(self.settings_predict_variance_checkbox)
        self.settings_predict_1_deg_der_mean_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_predict_1_deg_der_mean_checkbox.setObjectName("settings_predict_1_deg_der_mean_checkbox")
        self.settings_predict_verticalLayout.addWidget(self.settings_predict_1_deg_der_mean_checkbox)
        self.settings_predict_2_deg_der_mean_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_predict_2_deg_der_mean_checkbox.setObjectName("settings_predict_2_deg_der_mean_checkbox")
        self.settings_predict_verticalLayout.addWidget(self.settings_predict_2_deg_der_mean_checkbox)
        self.settings_predict_verticalLayout_3.addLayout(self.settings_predict_verticalLayout)
        self.gridLayout_2.addLayout(self.settings_predict_verticalLayout_3, 7, 0, 1, 1)
        self.settings_classify_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_classify_label.setObjectName("settings_classify_label")
        self.gridLayout_2.addWidget(self.settings_classify_label, 1, 0, 1, 1)
        self.settings_classify_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.settings_classify_verticalLayout_1.setObjectName("settings_classify_verticalLayout_1")
        self.settings_classify_features_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_classify_features_label.setObjectName("settings_classify_features_label")
        self.settings_classify_verticalLayout_1.addWidget(self.settings_classify_features_label)
        self.settings_classify_verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.settings_classify_verticalLayout_5.setObjectName("settings_classify_verticalLayout_5")
        self.settings_classify_mean_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_classify_mean_checkbox.setObjectName("settings_classify_mean_checkbox")
        self.settings_classify_verticalLayout_5.addWidget(self.settings_classify_mean_checkbox)
        self.settings_classify_variance_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_classify_variance_checkbox.setObjectName("settings_classify_variance_checkbox")
        self.settings_classify_verticalLayout_5.addWidget(self.settings_classify_variance_checkbox)
        self.settings_classify_1_deg_der_mean_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_classify_1_deg_der_mean_checkbox.setObjectName("settings_classify_1_deg_der_mean_checkbox")
        self.settings_classify_verticalLayout_5.addWidget(self.settings_classify_1_deg_der_mean_checkbox)
        self.settings_classify_2_deg_der_mean_checkbox = QtWidgets.QCheckBox(self.settings_scrollAreaWidgetContents)
        self.settings_classify_2_deg_der_mean_checkbox.setObjectName("settings_classify_2_deg_der_mean_checkbox")
        self.settings_classify_verticalLayout_5.addWidget(self.settings_classify_2_deg_der_mean_checkbox)
        self.settings_classify_verticalLayout_1.addLayout(self.settings_classify_verticalLayout_5)
        self.gridLayout_2.addLayout(self.settings_classify_verticalLayout_1, 2, 0, 1, 1)
        self.settings_info_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_info_label.setStyleSheet("QLabel:{\n"
"    text-decoration: underline\n"
"}")
        self.settings_info_label.setObjectName("settings_info_label")
        self.gridLayout_2.addWidget(self.settings_info_label, 0, 0, 1, 1)
        self.settings_classify_verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.settings_classify_verticalLayout_3.setObjectName("settings_classify_verticalLayout_3")
        self.settings_classify_overlap_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_classify_overlap_label.setObjectName("settings_classify_overlap_label")
        self.settings_classify_verticalLayout_3.addWidget(self.settings_classify_overlap_label)
        self.settings_classify_overlap_lineEdit = QtWidgets.QLineEdit(self.settings_scrollAreaWidgetContents)
        self.settings_classify_overlap_lineEdit.setObjectName("settings_classify_overlap_lineEdit")
        self.settings_classify_verticalLayout_3.addWidget(self.settings_classify_overlap_lineEdit)
        self.gridLayout_2.addLayout(self.settings_classify_verticalLayout_3, 4, 0, 1, 1)
        self.settings_predict_verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.settings_predict_verticalLayout_4.setObjectName("settings_predict_verticalLayout_4")
        self.settings_predict_window_len_label = QtWidgets.QLabel(self.settings_scrollAreaWidgetContents)
        self.settings_predict_window_len_label.setObjectName("settings_predict_window_len_label")
        self.settings_predict_verticalLayout_4.addWidget(self.settings_predict_window_len_label)
        self.settings_predict_window_len_lineEdit = QtWidgets.QLineEdit(self.settings_scrollAreaWidgetContents)
        self.settings_predict_window_len_lineEdit.setObjectName("settings_predict_window_len_lineEdit")
        self.settings_predict_verticalLayout_4.addWidget(self.settings_predict_window_len_lineEdit)
        self.gridLayout_2.addLayout(self.settings_predict_verticalLayout_4, 8, 0, 1, 1)
        self.settings_scrollArea.setWidget(self.settings_scrollAreaWidgetContents)
        self.tabWidget.addTab(self.settings_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Welcome to Cedrata Detector. </span></p><p>This is a ML based tool able to detect where notes are played in audio files.</p><p>The workflow to follow is simple, just follow the tab order:</p><p><br/></p><p>In the <span style=\" font-weight:600;\">classify </span>tab it\'s possible to classify reference audio samples, those will be what you consider a note. <br/>The machine will learn and retrive a file to use in the prediction tab.</p><p><br/></p><p>In the <span style=\" font-weight:600;\">predict </span>tab it\'s possible to use the classification file and use it as a reference on a selected audio track. <br/>The result will be a csv file containing two columns named &quot;sample&quot; and rname (wich is a field to fill). <br/>The audio is divided in multiple chuncks overlapping one each other, &quot;sample&quot; refers to the chunk number, <br/>rname is a value from 1 to 5, where 5 is certanly a note, and 1 is not at all a note.</p><p><br/></p><p>In the <span style=\" font-weight:600;\">merge </span>tab, after few files have been classified and predicted, is it possible to merge all the result in one csv file.</p><p><br/></p><p>Finally the <span style=\" font-weight:600;\">settings</span> tab will let you choose which features to use in the classification and prediction, <br/>length of each chunk, and the overlap starting point. To have a 1/10 sec precision, the suggested values are: <br/>overlap of 4410 and window length of 8820. Every analyzed audio is resampled in 44100Hz.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.classify_source_label.setText(_translate("MainWindow", "Source: select the folder containing the audio samples to classify"))
        self.classify_source_browse.setText(_translate("MainWindow", "Browse"))
        self.classify_destination_select.setText(_translate("MainWindow", "Destination: select the folder where the features will be extracted.<br/>\n"
"*.arrf file will be generated, in selected folder, named after \"relation name\", <br/>\n"
"if such files already exists, they will be overwritten."))
        self.classify_destination_browse.setText(_translate("MainWindow", "Browse"))
        self.clssify_relation_label.setText(_translate("MainWindow", "Insert the relation name"))
        self.classify_info_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">In this section you will be able to classify your samples, and create new instruments classifications.<br/>\n"
"A model to use in the \"Predict\" section will also be generate.</p></body></html>"))
        self.classify_start_button.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.classify_tab), _translate("MainWindow", "Classify"))
        self.predict_info_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">In this section you will be able to make predictions, based on the classifications created in the \"Classify\" section, <br>so temporaly locate notes on audio files</p></body></html>"))
        self.predict_source_label.setText(_translate("MainWindow", "Source: select the audio file to analyze"))
        self.predict_source_browse.setText(_translate("MainWindow", "Browse"))
        self.predict_start_button.setText(_translate("MainWindow", "Start"))
        self.predict_destination_select.setText(_translate("MainWindow", "Destination: select the folder where the *,csv file with informations will be stored"))
        self.predict_destination_browse.setText(_translate("MainWindow", "Browse"))
        self.predict_relation_label.setText(_translate("MainWindow", "Reference: select the *.arff file to use during the prediction"))
        self.predict_relation_browse.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.predict_tab), _translate("MainWindow", "Predict"))
        self.merge_info_label.setText(_translate("MainWindow", "<html><head/><body><p>In this section you can select multiple *.csv files to compare generating a new one. <br/>The new one will include the informations of all selected files</p></body></html>"))
        self.merge_select_button.setText(_translate("MainWindow", "Browse"))
        self.merge_destination_label.setText(_translate("MainWindow", "Select the destination"))
        self.merge_destination_browse.setText(_translate("MainWindow", "Browse"))
        self.merge_start_button.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.merge_tab), _translate("MainWindow", "Merge"))
        self.settings_predict_overlap_label.setText(_translate("MainWindow", "Overlap distance (sampels before starting overlap)"))
        self.settings_reset_button.setText(_translate("MainWindow", "Reset"))
        self.settings_apply_button.setText(_translate("MainWindow", "Apply"))
        self.settings_predict_label.setText(_translate("MainWindow", "Predict Settings:"))
        self.settings_classify_window_len_label.setText(_translate("MainWindow", "Window length (samples lenght)"))
        self.settings_predict_features_label.setText(_translate("MainWindow", "Features"))
        self.settings_predict_mean_checkbox.setText(_translate("MainWindow", "mean"))
        self.settings_predict_variance_checkbox.setText(_translate("MainWindow", "variance"))
        self.settings_predict_1_deg_der_mean_checkbox.setText(_translate("MainWindow", "1st deg mean derivative"))
        self.settings_predict_2_deg_der_mean_checkbox.setText(_translate("MainWindow", "2nd deg mean derivative"))
        self.settings_classify_label.setText(_translate("MainWindow", "Classify Settings:"))
        self.settings_classify_features_label.setText(_translate("MainWindow", "Features"))
        self.settings_classify_mean_checkbox.setText(_translate("MainWindow", "mean"))
        self.settings_classify_variance_checkbox.setText(_translate("MainWindow", "variance"))
        self.settings_classify_1_deg_der_mean_checkbox.setText(_translate("MainWindow", "1st deg mean derivative"))
        self.settings_classify_2_deg_der_mean_checkbox.setText(_translate("MainWindow", "2nd deg mean derivative"))
        self.settings_info_label.setText(_translate("MainWindow", "It is reccomended to have the same settings for prediction and classification"))
        self.settings_classify_overlap_label.setText(_translate("MainWindow", "Overlap distance (sampels before starting overlap)"))
        self.settings_predict_window_len_label.setText(_translate("MainWindow", "Window length (samples lenght)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
